name: 'Training Theme'
type: theme
base theme: bootstrap_barrio
description: 'Custom theme for the Drupal Training Portal'
package: Custom
core_version_requirement: ^10 || ^11

libraries:
  - training_theme/global-styling

regions:
  header: Header
  primary_menu: 'Primary Menu'
  hero: Hero
  highlighted: Highlighted
  content: Content
  sidebar_first: 'Sidebar'
  footer: Footer
